from typing import Any

import h5py._objects

def attach_scale(*args, **kwargs) -> Any: ...
def detach_scale(*args, **kwargs) -> Any: ...
def get_label(*args, **kwargs) -> Any: ...
def get_num_scales(*args, **kwargs) -> Any: ...
def get_scale_name(*args, **kwargs) -> Any: ...
def is_attached(*args, **kwargs) -> Any: ...
def is_scale(*args, **kwargs) -> Any: ...
def iterate(*args, **kwargs) -> Any: ...

phil: h5py._objects.FastRLock

def set_label(*args, **kwargs) -> Any: ...
def set_scale(*args, **kwargs) -> Any: ...

class _DimensionScaleVisitor:
    def __init__(self, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

def with_phil(*args, **kwargs) -> Any: ...
