from typing import Any

def append(*args, **kwargs) -> Any: ...
def get(*args, **kwargs) -> Any: ...
def insert(*args, **kwargs) -> Any: ...
def prepend(*args, **kwargs) -> Any: ...
def remove(*args, **kwargs) -> Any: ...
def replace(*args, **kwargs) -> Any: ...
def size(*args, **kwargs) -> Any: ...
