from typing import Any, ClassVar

import h5py._objects

DATASET_REGION: int
OBJECT: int

def create(*args, **kwargs) -> Any: ...
def dereference(*args, **kwargs) -> Any: ...
def get_name(*args, **kwargs) -> Any: ...
def get_obj_type(*args, **kwargs) -> Any: ...
def get_region(*args, **kwargs) -> Any: ...

phil: h5py._objects.FastRLock

class Reference:
    typecode: Any
    typesize: Any
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    def __bool__(self) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class RegionReference(Reference):
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

def with_phil(*args, **kwargs) -> Any: ...
