from typing import Any, ClassVar

import h5py._objects

ALL: SpaceID
NO_CLASS: int
NULL: int
SCALAR: int
SELECT_AND: int
SELECT_APPEND: int
SELECT_INVALID: int
SELECT_NOOP: int
SELECT_NOTA: int
SELECT_NOTB: int
SELECT_OR: int
SELECT_PREPEND: int
SELECT_SET: int
SELECT_XOR: int
SEL_ALL: int
SEL_ERROR: int
SEL_HYPERSLABS: int
SEL_NONE: int
SEL_POINTS: int
SIMPLE: int
UNLIMITED: int

def create(*args, **kwargs) -> Any: ...
def create_simple(*args, **kwargs) -> Any: ...
def decode(*args, **kwargs) -> Any: ...

phil: h5py._objects.FastRLock

class SpaceID(h5py._objects.ObjectID):
    shape: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def copy(self, *args, **kwargs) -> Any: ...
    def encode(self, *args, **kwargs) -> Any: ...
    def extent_copy(self, *args, **kwargs) -> Any: ...
    def get_regular_hyperslab(self, *args, **kwargs) -> Any: ...
    def get_select_bounds(self, *args, **kwargs) -> Any: ...
    def get_select_elem_npoints(self, *args, **kwargs) -> Any: ...
    def get_select_elem_pointlist(self, *args, **kwargs) -> Any: ...
    def get_select_hyper_blocklist(self, *args, **kwargs) -> Any: ...
    def get_select_hyper_nblocks(self, *args, **kwargs) -> Any: ...
    def get_select_npoints(self, *args, **kwargs) -> Any: ...
    def get_select_type(self, *args, **kwargs) -> Any: ...
    def get_simple_extent_dims(self, *args, **kwargs) -> Any: ...
    def get_simple_extent_ndims(self, *args, **kwargs) -> Any: ...
    def get_simple_extent_npoints(self, *args, **kwargs) -> Any: ...
    def get_simple_extent_type(self, *args, **kwargs) -> Any: ...
    def is_regular_hyperslab(self, *args, **kwargs) -> Any: ...
    def is_simple(self, *args, **kwargs) -> Any: ...
    def offset_simple(self, *args, **kwargs) -> Any: ...
    def select_all(self, *args, **kwargs) -> Any: ...
    def select_elements(self, *args, **kwargs) -> Any: ...
    def select_hyperslab(self, *args, **kwargs) -> Any: ...
    def select_none(self, *args, **kwargs) -> Any: ...
    def select_valid(self, *args, **kwargs) -> Any: ...
    def set_extent_none(self, *args, **kwargs) -> Any: ...
    def set_extent_simple(self, *args, **kwargs) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

def with_phil(*args, **kwargs) -> Any: ...
