from typing import Any

from .. import h5, h5a, h5p, h5s, h5t
from . import base
from .base import Empty, is_empty_dataspace, phil, product, with_phil
from .datatype import Datatype

class AttributeManager(base.MutableMappingHDF5, base.CommonStateObject):
    def __init__(self, parent) -> None: ...
    def __getitem__(self, name): ...
    def get_id(self, name): ...
    def __setitem__(self, name, value) -> None: ...
    def __delitem__(self, name) -> None: ...
    def create(
        self, name, data, shape: Any | None = ..., dtype: Any | None = ...
    ) -> None: ...
    def modify(self, name, value) -> None: ...
    def __len__(self): ...
    def __iter__(self): ...
    def __contains__(self, name): ...
