from typing import Any

from .. import h5s

def read_dtypes(dataset_dtype, names): ...
def read_selections_scalar(dsid, args): ...

class ScalarReadSelection:
    mshape: Any
    mspace: Any
    fspace: Any
    def __init__(self, fspace, args) -> None: ...
    def __iter__(self): ...

def select_read(fspace, args): ...
